version: "3.8"
services:
  mysql:
    container_name: departments-app_db
    image: mysql:8.0.31
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3366:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 10s
      retries: 3

  backend:
    container_name: departments-app_backend
    build: ./backend/
    volumes:
      - ./backend/logs:/app/logs
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3366
    ports:
      - "3030:3030"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    container_name: departments-app_frontend
    build:
      context: ./frontend/
      dockerfile: ${DOCKERFILE}
    environment:
      - DOCKERFILE=Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db: